import json
import os
from pathlib import Path
from typing import Dict, List

import requests

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN")
OWNER = "frasermolyneux"
REPO = "platform-workloads"
WORKLOADS_PATH = "terraform/workloads"
OUTPUT_FILE = Path(__file__).resolve().parents[2] / "docs" / "estate" / "workloads.md"

session = requests.Session()
session.headers.update({"Authorization": f"Bearer {GITHUB_TOKEN}", "Accept": "application/vnd.github+json"})


def github_contents(path: str) -> List[Dict]:
    url = f"https://api.github.com/repos/{OWNER}/{REPO}/contents/{path}"
    resp = session.get(url)
    resp.raise_for_status()
    return resp.json()


def load_workloads() -> Dict[str, List[Dict]]:
    categories: Dict[str, List[Dict]] = {}
    for entry in github_contents(WORKLOADS_PATH):
        if entry["type"] != "dir" or entry["name"] == "examples":
            continue
        category = entry["name"]
        categories[category] = []
        for file_entry in github_contents(f"{WORKLOADS_PATH}/{category}"):
            if file_entry["type"] != "file" or not file_entry["name"].endswith(".json"):
                continue
            raw = session.get(file_entry["download_url"])
            raw.raise_for_status()
            payload = json.loads(raw.text)
            categories[category].append({
                "name": payload.get("name", file_entry["name"].replace(".json", "")),
                "repo": payload.get("name", file_entry["name"].replace(".json", "")),
                "environments": [env.get("name") for env in payload.get("environments", [])],
            })
    return categories


def render(categories: Dict[str, List[Dict]]) -> str:
    lines = [
        "# Workload Catalog",
        "",
        "Generated from platform-workloads/terraform/workloads (excluding examples).",
        "",
    ]
    for category in sorted(categories.keys()):
        lines.append(f"## {category}")
        lines.append("")
        lines.append("| Workload | Environments |")
        lines.append("| --- | --- |")
        for workload in sorted(categories[category], key=lambda w: w["name"]):
            envs = ", ".join([env for env in workload["environments"] if env]) or "-"
            lines.append(f"| {workload['name']} | {envs} |")
        lines.append("")
    lines.append("---")
    lines.append("Generated by scripts/estate-sync/estate_sync.py")
    return "\n".join(lines)


def main() -> None:
    categories = load_workloads()
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(render(categories), encoding="utf-8")


if __name__ == "__main__":
    if not GITHUB_TOKEN:
        raise SystemExit("GITHUB_TOKEN is required")
    main()
